name: Deploy to ndtho8205.github.io

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout `blog` repository
      uses: actions/checkout@v2
      with:
        submodules: true
        path: blog

    - name: Checkout `blog-theme` repository
      uses: actions/checkout@v2
      with:
        path: blog-theme

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.71.1'
        extended: true
        
    - name: Clean `public` diretory
      run: find $GITHUB_WORKSPACE/blog/public/ \! -name '.git' -delete
    
    - name: Build hugo
      run: cd $GITHUB_WORKSPACE/blog && hugo --minify --gc

    - name: Show tree
      run: tree
